# Generated by Django 3.2.18 on 2023-03-20 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_is_noob_user_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_Staff',
            new_name='is_staff',
        ),
    ]
